apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
- namespace.yaml
- deployment.yaml
- oauth.yaml
configMapGenerator:
- name: homepage-site
  files:
  - index.html=../site/index.html
generatorOptions:
  disableNameSuffixHash: false
